config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  resources :tiny_houses do
    collection do
      get :mine
      get :my_rents
    end
    resources :rents, only: [:new, :create]
  end
  resources :users, only: :show

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :tiny_house
end

app/models/tiny_house.rb
class TinyHouse < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :rents

  mount_uploader :photo, PhotoUploader

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rents
  has_many :tiny_houses, through: :rents # locataire
  has_many :own_tiny_houses, class_name: 'TinyHouse', foreign_key: :owner_id
end

# User.last.tiny_houses     => tiny_houses locataire
# User.last.own_tiny_houses => tiny_houses proprio

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController

  # def new
  #   @tiny_house = TinyHouse.find(params[:tiny_house_id])
  #   @rent = Rent.new
  # end

  def create
    @rent = Rent.new(rent_params)
    @tiny_house = TinyHouse.find(params[:tiny_house_id])
    @rent.tiny_house_id = params[:tiny_house_id]
    @rent.user_id = current_user.id 
    if @rent.save
        redirect_to my_rents_tiny_houses_path, notice: 'Rent was successfully created.'
    else
        render 'tiny_houses/show'
    end
  end

  private

  def rent_params
    params.require(:rent).permit(:date)
  end
end

app/controllers/tiny_houses_controller.rb
class TinyHousesController < ApplicationController
  def index
    @tiny_houses = TinyHouse.all

    @tiny_houses = TinyHouse.geocoded #returns tinyhouses with coordinates
    @markers = @tiny_houses.map do |tiny|
      {
        lat: tiny.latitude,
        lng: tiny.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { tiny: tiny }),
        image_url: helpers.asset_url('tiny-pin.svg')
      }
    end
  end

  def mine
    @my_tiny_houses = current_user.own_tiny_houses

  end

  def my_rents
    @rent_tiny_houses = current_user.tiny_houses
  end

  def show
    @tiny_house = TinyHouse.geocoded
    @tiny_house = TinyHouse.find(params[:id])
    # tiny = @tiny_house
    @markers = [
      lat: @tiny_house.latitude,
      lng: @tiny_house.longitude,
      infoWindow: render_to_string(partial: "info_window",  locals: { tiny: @tiny_house }),
      image_url: helpers.asset_url('tiny-pin.svg')
    ]
    @rent = Rent.new
  end

  def new
    @tiny_house = TinyHouse.new
  end

  def create
    @tiny_house = TinyHouse.new(tiny_house_params)
    @tiny_house.owner = current_user
    if @tiny_house.save
      redirect_to tiny_house_path(@tiny_house)
    else
      render :new
    end
  end

  def edit
    @tiny_house = TinyHouse.find(params[:id])
  end

  def update
    @tiny_house = TinyHouse.find(params[:id])
    @tiny_house.update(tiny_house_params)

    redirect_to '/tiny_houses', notice: 'Tiny House updated successfully!'
  end

  def destroy
    @tiny_house = TinyHouse.find(params[:id])
    @tiny_house.destroy

    redirect_to '/tiny_houses', notice: "#{@tiny_house.title} deleted successfully!"
  end

  private

  def tiny_house_params
    params.require(:tiny_house).permit(
      :title,
      :description,
      :location,
      :travellers_number,
      :price,
      :bed_number,
      :bedroom_number,
      :sauna,
      :kitchen,
      :wifi,
      :photo
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def update?
    record.user == user
  end

  def destroy?
    record.user == user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tiny Airbnb</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>


      <%= render 'shared/footer' %>

      <%= javascript_include_tag 'application' %>
      <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="herobanner">
    <div class="main-title">
      <div class="title">
        <h1>Connect with Nature with our Tiny Houses</h1>
      </div>
        <div id="typed-strings">
          <p>Disconnect...</p>
          <p>Meditate...</p>
          <p>Dream...</p>
        </div>
        <span id="typed"></span>
    </div>

    <div class="flex-buttons">
      <p id="home-signup-button"><%= link_to 'Sign Up', new_user_registration_path%></p>
      <p id="home-login"><%= link_to 'Log In', new_user_session_path%></p>
    </div>
  </div>
<div class="container">
  <div id="center-position">
    <button id="blackbutton-home"><%= link_to 'All our Tiny Houses', tiny_houses_path%></button>
  </div>
</div>

app/views/rents/_form_new_rent.html.erb
<%= simple_form_for [tiny_house, rent] do |f| %>
  <%= f.input :date %>
  <%= f.submit "Confirm rent", class: "btn btn-primary" %>
<% end %>

app/views/rents/new.html.erb
<h1>Rent new Tiny House</h1>

<%= simple_form_for [@tiny_house, @rent] do |f| %>
  <%= f.input :date %>
  <%= f.submit "add a rent", class: "btn btn-primary" %>
<% end %>

<%= link_to 'Back', tiny_houses_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <div class="footer-bg">
    <div class="container">

      <div class="flex-footer">
        <div class="left">
          <div class="contact-us">
            <div class="logo">
              <%= link_to '', class: "contact" do %>
                <%= image_tag("email-icon.svg") %>
              <% end %>
            </div>
            <div>
              <p>Nous Contacter</p>
            </div>
          </div>
          <p class="lewagon">Made with love at Le Wagon</p>
        </div>

        <div class="right">
          <div>
            <%= link_to '', class: "insta" do %>
              <%= image_tag("instagram-logo.svg") %>
            <% end %>
          </div>
          <div>
            <%= link_to '', class: "twitter" do %>
              <%= image_tag("twitter.svg") %>
            <% end %>
          </div>
          <div>
            <%= link_to '', class: "facebook" do %>
              <%= image_tag("facebook.svg") %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-tiny">
  <div class="container">
    <div class="logo">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag("logo-tiny.svg") %>
      <% end %>
    </div>

  <div class="menu-right">

    <div class="navbar-menu">
      <%= link_to "My Tiny Houses", mine_tiny_houses_path %>
    </div>

    <div class="navbar-menu">

      <%= link_to "My rents", my_rents_tiny_houses_path %>
    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <%= image_tag "profile-icon.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

app/views/tiny_houses/_form.html.erb
  <%= simple_form_for(@tiny_house) do |f| %>
    <%= f.input :title %>
    <%= f.input :description, as: :text, placeholder: 'Describe your Tiny' %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.input :location, placeholder: 'add Tiny address' %>
    <%= f.input :travellers_number %>
    <%= f.input :bed_number %>
    <%= f.input :bedroom_number %>
    <%= f.input :kitchen, as: :radio_buttons %>
    <%= f.input :wifi, as: :radio_buttons %>
    <%= f.input :sauna, as: :radio_buttons %>
    <%= f.input :price %>
    <%= f.hint 'price per night' %>
    <%= f.button :submit %>
  <% end %>

app/views/tiny_houses/_info_window.html.erb
<h5><%= tiny.title %></h5>
<p><%= cl_image_tag tiny.photo, height: 150, width: 200, crop: :fill %></p>
<p><%= tiny.price %> €/night</p>

app/views/tiny_houses/edit.html.erb
<h1>Editing Tinyhouse</h1>
<%= render 'form', tinyhouse: @tiny_house %>
<%= link_to 'Show', @tiny_house %>
<%= link_to 'Back', mine_tiny_houses_path %>

app/views/tiny_houses/index.html.erb
  <h1>All our Tiny Houses</h1>

<div class="contain d-flex">
<div class="cards">
  <% @tiny_houses.each do |tiny| %>
  <div class="card">
    <p class="photo-index"><%= cl_image_tag tiny.photo, height: 300, width: 250, crop: :fill %></p>
    <h2><%= tiny.title %></h2>
    <p><%= tiny.description %></p>
    <p><%= link_to 'show', tiny_house_path(tiny.id) %></p>

  </div>
  <% end %>
</div>


<div
  id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>
</div>

<h4><%= link_to 'Add a new Tiny House', new_tiny_house_path %></h4>

app/views/tiny_houses/mine.html.erb
<div class="container">
  <h1>My Tiny Houses </h1>

    <div class="cards">
      <% @my_tiny_houses.each do |tiny| %>
        <h2><%= tiny.title %></h2>
        <p><%= tiny.description %></p>
        <p class="photo-index"><%= cl_image_tag tiny.photo, height: 300, width: 400, crop: :fill %></p>
        <p><%= link_to 'show', tiny_house_path(tiny.id) %></p>
        <p><%= link_to 'edit', edit_tiny_house_path(tiny) %></p>
        <p><%= link_to 'delete', tiny_house_path(tiny), method: :delete, data: { confirm: "Are you sure ?" } %></p>
      <% end %>
    </div>

    <div class="user-info">
      <p>My Profil </p>
      <p> Name: John Doe </p>
      <p> Email: <%= current_user.email %> </p>
      <p> Telephone: 06-56-84-58-69</p>
      <p> Number of Tiny: <%= @my_tiny_houses.size %></p>
    </div>

  <button class="blackbutton"><%= link_to 'Add a new Tiny House', new_tiny_house_path %></button>
</div>

app/views/tiny_houses/my_rents.html.erb
<div class="container">
  <h1>Your rents</h1>

  <div class="cards">
    <% @rent_tiny_houses.each do |tiny| %>
      <h2><%= tiny.title %></h2>
        <p><%= tiny.description %></p>
        <p class="photo-index"><%= cl_image_tag tiny.photo, height: 300, width: 400, crop: :fill %></p>
        <p><%= link_to 'show', tiny_house_path(tiny.id) %></p>
    <% end %>
  </div>

  <button class="blackbutton"><%= link_to 'Add a new Tiny House', new_tiny_house_path %></button>
</div>

app/views/tiny_houses/new.html.erb
<h1>Add new Tiny House</h1>

<%= render 'form', tiny_house: @tiny_house %>


<%= link_to 'Show', @tiny_house %> |
<%= link_to 'Back', tiny_houses_path %>

app/views/tiny_houses/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1><%= @tiny_house.title %></h1>

    <div class="display">

      <div class="description">

        <div class="tiny-img">
          <p><%= cl_image_tag @tiny_house.photo, height: 500, width: 500, crop: :fill %></p>
        </div>

        <p>Description : <%= @tiny_house.description %></p>
        <p>Where is it? <%= @tiny_house.location %></p>
        <p>For <%= @tiny_house.travellers_number %> travellers</p>
        <p>With <%= @tiny_house.bed_number %> bed(s)</p>
        <p>With <%= @tiny_house.bedroom_number %> bedroom(s)</p>
        <p>Does it have a sauna? <%= @tiny_house.sauna %></p>
        <p>Does it have a kitchen? <%= @tiny_house.kitchen %></p>
        <p>Connected with Wifi? <%= @tiny_house.wifi %></p>
        <p>Price per night: <%= @tiny_house.price %>€</p>
      <% if @tiny_house.owner_id != current_user.id %>
      <br>
          <button class="bluebutton rent">Rent this Tiny House!</button>
        <% end%>

        <button class="blackbutton"><%= link_to 'All our Tiny Houses', tiny_houses_path(@tiny_house) %></button>
      </div>

      <div class="maptoright">
        <div
          id="map"
          style="width: 100%;
          height: 500px;
          border-radius: 8px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        ></div>



      </div>
    </div>





    <div id = "rent_form" style="display: none;">
    <%= render 'rents/form_new_rent', tiny_house: @tiny_house, rent: @rent %>
  </div>


</div>